---
title: "31 - MDSR Decision Trees"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Structure
Working to make a decision tree for the Bolivian data.

```{r}
library(mdsr)
```

# Separating into Testing and Training
I will have a sample of 80% of the rows as the training dataset, and 20% for the testing dataset.

```{r}
#Setting the seed
set.seed(364)

#Getting the number of rows
n <- nrow(labelled_wide)
#Getting .2 of `labelled_wide`
test <- sample.int(n, size = round(0.2 * n))
#Making training dataset
train <- labelled_wide[-test, ]
#Checking length
nrow(train)

#Making testing dataset
test <- labelled_wide[test, ]
#Checking length
nrow(test)

#Making sure the training and testing datasets add up to `labelled_wide`
nrow(labelled_wide)
nrow(train) + nrow(test)
```

```{r}
tally(~ police_bribe, data = train)
```

I am going to try to find a split for ideology based on one variable first, urban vs. rural.

```{r}
library(rpart)
```

```{r}
test <- rpart(police_bribe ~ urbano_rural + sexo + edad, data = train,
      method = "class",
      minsplit = 1,
      minbucket = 1,
      cp = 0)
```

```{r}
plot(as.party(test))
```

Only getting one node here.

# !DO NOT USE REFERENCE ONLY
#```{r}
# ggplot(data = train, aes(x = police_bribe, y = urbano_rural)) +
#   geom_count(aes(color = urbano_rural),
# position = position_jitter(width = 0, height = 0.1), alpha = 0.5)
#```

```{r}
formula <- as.formula("police_bribe ~ .")
mod_tree <- rpart(formula,
                  data = train,
                  method = "class",
                  minsplit = 1,
                  minbucket = 1,
                  cp = -1)
mod_tree
```

```{r}
library(partykit)
```

```{r}
plot(as.party(mod_tree))
```


